title: Net Full of Fish
baseurl: ''
description: ''
author:
    name: 'Keith Walbolt'

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
plugins:
    - jekyll-paginate

collections:
  microblog:
    output: true
    permalink: /microblog/:year/:month/:slug/